# This file created by conda-build 2.1.16
# meta.yaml template originally from:
# /Users/swoboj/Documents/Python/conda-recipes/log4cpp, last modified Fri Jun 30 16:28:55 2017
# ------------------------------------------------

package:
    name: log4cpp
    version: 1.1.1
source:
    sha256: 35abf332630a6809c969276b1d60b90c81a95daf24c86cfd7866ffef72f9bed0
    url: https://downloads.sourceforge.net/project/log4cpp/log4cpp-1.1.x (new)/log4cpp-1.1/log4cpp-1.1.1.tar.gz
build:
    detect_binary_files_with_prefix: 'True'
    noarch: ''
    noarch_python: false
    number: '1'
    string: '1'
requirements:
    build:
        - autoconf 2.69 0
        - m4 1.4.17 0
        - llvm 3.3 0
    run: []
about:
    description: 'Log for C++ is a library of C++ classes for flexible logging to
        files,

        syslog and other destinations. It is modeled after the Log for Java library

        (http://jakarta.apache.org/log4j/), staying as close to their API as is

        reasonable.

        '
    dev_url: http://git.code.sf.net/p/log4cpp/codegit
    doc_url: http://log4cpp.sourceforge.net/api/index.html
    home: http://log4cpp.sourceforge.net
    license: LGPL-2.1
    license_file: COPYING
    summary: C++ library for flexible logging
extra:
    final: true
    recipe-maintainers:
        - ryanvolz
