{% set name = "digital_rf" %}
{% set version = "2.3.0rc1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/ryanvolz/{{ name }}.git
  git_rev: {{ version }}

build:
  number: 0
  detect_binary_files_with_prefix: True

requirements:
  build:
    - toolchain
    - python >=2.7,<3
    - numpy
    - hdf5
    - pkg-config
    - pkgconfig
  run:
    - python >=2.7,<3
    - numpy
    - hdf5
    - h5py

test:
  imports:
    - digital_rf_hdf5
    - digital_metadata
  source_files:
    - testing/*.py
    - examples/*.py
  commands:
    - python testing/test_digital_rf_hdf5.py
    - rm -r /tmp/hdf5*
    - python examples/example_write_digital_metadata.py
    - python examples/example_read_digital_metadata.py
    - rm -r /tmp/test_metadata/
