package:
  name: digital_rf
  version: 1.1.3

source:
  git_url: https://github.com/ryanvolz/digital_rf.git
  git_rev: 1.1.3

requirements:
  build:
    - python
    - numpy x.x
    - hdf5
    - pkgconfig
  run:
    - python
    - numpy
    - h5py

test:
  imports:
    - digital_rf_hdf5
    - digital_metadata
