{% set name = "digital_rf" %}
{% set version = "2.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: git@github.mit.edu:/rvolz/{{ name }}.git
  git_rev: {{ version }}

build:
  number: 0
  detect_binary_files_with_prefix: True

requirements:
  build:
    - toolchain
    - python >=2.7,<3
    - numpy
    - hdf5 >=1.8
    - gnuradio
    - boost 1.62.*
    - swig
    - cppunit
  run:
    - python >=2.7,<3
    - hdf5 >=1.8
    - gnuradio
    - boost 1.62.*
    - numpy
    - h5py
    - matplotlib
    - scipy
    - watchdog
    # extra requirements for thor script
    - pytz
    - dateutil

test:
  imports:
    - digital_rf
    - digital_rf.digital_rf_hdf5
  source_files:
    - tests/*.py
    - examples/*.py
  commands:
    - python tests/test_digital_rf_hdf5.py
    - rm -r /tmp/hdf5*
    - python examples/example_write_digital_metadata.py
    - python examples/example_read_digital_metadata.py
    - rm -r /tmp/test_metadata/
