{% set name = "digital_rf" %}
{% set version = "2.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/ryanvolz/{{ name }}.git
  git_rev: {{ version }}

build:
  number: 0
  detect_binary_files_with_prefix: True

requirements:
  build:
    - toolchain
    - python >=2.7,<3
    - numpy
    - hdf5
    - pkg-config
    - pkgconfig
  run:
    - python >=2.7,<3
    - numpy
    - h5py

test:
  imports:
    - digital_rf_hdf5
    - digital_metadata
