{% set name = "gr-drf" %}
{% set version = "2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/ryanvolz/{{ name }}.git
#  git_rev: v{{ version }}
  git_rev: v2.0rc1

build:
  number: 12
  detect_binary_files_with_prefix: True

requirements:
  build:
    - toolchain
    - pkg-config
    - python >=2.7,<3
    - boost 1.62.*
    - swig
    - hdf5
    - gnuradio
    - digital_rf >2.2
    - cppunit
    - numpy
  run:
    - python >=2.7,<3
    - boost 1.62.*
    - hdf5
    - gnuradio
    - digital_rf >2.2
    - numpy
    # extra requirements for thor script
    - pytz
    - dateutil

test:
  imports:
    - gr_drf

  commands:
    - python -c "from gr_drf import digital_rf_sink"
