{% set name = "gr-drf" %}
{% set version = "2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/ryanvolz/{{ name }}.git
#  git_rev: v{{ version }}
  git_rev: v2.0b9

build:
  number: 8
  detect_binary_files_with_prefix: True

requirements:
  build:
    - toolchain
    - pkg-config
    - python >=2.7,<3
    - boost 1.62.*
    - swig
    - hdf5
    - gnuradio
    - digital_rf >=2.0
    - cppunit
  run:
    - python >=2.7,<3
    - boost 1.62.*
    - hdf5
    - gnuradio
    - digital_rf
    # extra requirements for thor script
    - pytz
    - dateutil

test:
  imports:
    - drf

  commands:
    - python -c "from drf import digital_rf_sink"
