package:
  name: uhd
  version: 3.9.4

source:
  git_url: https://github.com/EttusResearch/uhd.git
  git_rev: release_003_009_004

build:
  number: 0
  detect_binary_files_with_prefix: True

requirements:
  build:
    - toolchain
    - pkg-config
    - cmake >=2.8
    - boost >=1.53
    - python >=2.7
    - mako >=0.5.0
#    - doxygen
#    - libusb

  run:
    - python >=2.7
    - requests
